language: go

go:
- 1.3.3

matrix:
  fast_finish: true

env:
  global:
    secure: fsER+MwkU8XHPIbG9GMtBANX6nUTqNH4CGev5Tiu5N/GCRcnQYZXcBBPgU89zhw+S0Ru31bGkXvSfyplXckoQTUsPOYD6uRUQweuR/MsPseiZ9uCoYhpOTsCHuSxD66+94RDithYAwKI5ooUvwDRqFD+dsBazrk5Sj3MiOnKdgU=

install:
- export GOBIN=$HOME/bin
- export PATH=$GOBIN:$PATH
- mkdir $HOME/gopath/src/github.com/rjeczalik && mv $HOME/gopath/src/github.com/yaey8Hee/Oong7Pha $HOME/gopath/src/github.com/rjeczalik/notify
- go get code.google.com/p/go.tools/cmd/vet code.google.com/p/go.tools/cmd/cover github.com/mattn/goveralls github.com/modocache/gover gopkg.in/fsnotify.v1
- go get -t -v ./...
- go install -a -race std

script:
- go tool vet -all .
- go build ./...
- go test -race -v ./...
- go list -f '{{if len .TestGoFiles}}go test -coverprofile={{.Dir}}/.coverprofile {{.ImportPath}}{{end}}' ./... | xargs -i sh -c {}
- gover
- goveralls -coverprofile=gover.coverprofile -service=travis-ci -repotoken $COVERALLS_TOKEN
